#!/usr/bin/env bash
# Build a "DRAFT-PREVIEW" PDF of the paper using the synthetic example_run data.
#
# This exists so the layout (column widths, table placement, figure
# position, page count) can be inspected before committing to a 30+ hour
# real run. The synthetic data is generated by a deterministic random
# script and is clearly marked in the output.
#
# IMPORTANT: this PDF is NOT a submission artifact. It is a layout preview.
#
# Output: paper_preview/main.pdf with a red "DRAFT (synthetic data)" watermark.

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PAPER="$(cd "$ROOT/.." && pwd)/paper"
PREVIEW="$(cd "$ROOT/.." && pwd)/paper_preview"

# 1. Regenerate synthetic trials.jsonl deterministically.
python -m results.example_run.regen_synthetic 2>/dev/null \
  || python "$ROOT/results/example_run/regen_synthetic.py"

# 2. Mirror paper/ to paper_preview/ and overwrite tables + figures with
#    the synthetic-data outputs so paper/tables/ stays TODO for real submission.
rm -rf "$PREVIEW"
mkdir -p "$PREVIEW"
cp -r "$PAPER/." "$PREVIEW/"

python -m execugraph.analysis.build_tables  "$ROOT/results/example_run" --out "$PREVIEW/tables"
python -m execugraph.analysis.build_figures "$ROOT/results/example_run" --out "$PREVIEW/figures"

# 3. Inject a DRAFT watermark at the top of main.tex.
PREVIEW_PY="$(echo "$PREVIEW" | sed 's|\\|/|g')"
PREVIEW_PY="$PREVIEW_PY" python -c '
import os
from pathlib import Path
p = Path(os.environ["PREVIEW_PY"]) / "main.tex"
src = p.read_text(encoding="utf-8")
header = (
    r"% DRAFT-PREVIEW: numbers in this PDF are SYNTHETIC and produced by "
    r"results/example_run/regen_synthetic.py. Do NOT cite or submit." "\n"
    r"\usepackage{draftwatermark}" "\n"
    r"\SetWatermarkText{DRAFT * synthetic data}" "\n"
    r"\SetWatermarkScale{0.6}" "\n"
    r"\SetWatermarkLightness{0.92}" "\n"
)
src = src.replace(r"\documentclass[journal]{IEEEtran}",
                  r"\documentclass[journal]{IEEEtran}" "\n" + header)
p.write_text(src, encoding="utf-8")
print("watermark injected")
'

# 4. Compile.
cd "$PREVIEW"
pdflatex -interaction=nonstopmode main.tex >/dev/null 2>&1 || true
bibtex main >/dev/null 2>&1 || true
pdflatex -interaction=nonstopmode main.tex >/dev/null 2>&1 || true
pdflatex -interaction=nonstopmode main.tex >/dev/null 2>&1 || true
ls -la main.pdf
echo "Preview written to $PREVIEW/main.pdf"
